version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release

platform: Any CPU

build:
  project: src\Dnn.PersonaBar.Extensions.sln
  parallel: true
  verbosity: minimal

test:
  assemblies:
    - '*.Tests.dll'
