version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release

platform: Any CPU

build:
  project: src\Dnn.PersonaBar.Extensions.sln
  parallel: true
  verbosity: minimal
  
before_package:		
  ps: .\build\YarnInstall.ps1 .\src

test:
  assemblies:
    - '*.Tests.dll'
