version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: true
configuration: Release
platform: Any CPU
nuget:
  disable_publish_on_pr: true
build:
  project: src\Dnn.PersonaBar.Extensions.sln
  parallel: true
  verbosity: minimal
cache: "%LOCALAPPDATA%\\Yarn"
